trigger:
  - main

jobs:
  - job: StageProvisionServer
    displayName: "Stage: Provision Server"
    pool: default
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: "Resource Group"
          azureResourceManagerConnection: "ServiceConnectionProjectAnsible"
          subscriptionId: "c0b52ba4-df61-49cf-ab65-315eb1152086"
          action: "Create Or Update Resource Group"
          resourceGroupName: "ResourceGroupBeroepsProduct"
          location: "West Europe"
          templateLocation: "Linked artifact"
          csmFile: "$(System.DefaultWorkingDirectory)/Server/ARM/parameters.bicepparam"
          csmParametersFile: "$(System.DefaultWorkingDirectory)/Server/ARM/template.bicep"
          deploymentMode: "Incremental"
