trigger:
  - main

pool: default

stages:
  - stage: StageProvisionServer
    displayName: "Stage: Provision Server"
    jobs:
      - job: JobProvisionServer
        displayName: "Job: Provision Server"
        variables:
          vmUsername: $(vmUsername)
          vmPassword: $(vmPassword)
          AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: true
        steps:
          - checkout: none
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/Server/script/DeployVM.ps1"
              azurePowerShellVersion: "LatestVersion"
              pwsh: true
