trigger:
  - main

pool:
  vmImage: "windows-latest"

stages:
  - stage: StageProvisionServer
    displayName: "Stage: Provision Server"
    jobs:
      - job: JobProvisionServer
        displayName: "Job: Provision Server"
        variables:
          vmUsername: $(vmUsername)
          vmPassword: $(vmPassword)
        steps:
          - checkout: none
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/Server/script/DeployVM.ps1"
              azurePowerShellVersion: "LatestVersion"
              pwsh: true
            env:
              vmUsername: $(vmUsername)
              vmPassword: $(vmPassword)
