trigger: none

pool:
  vmImage: 'ubuntu-latest'

# pool: "" ## Enable if self-Hosted agents are used (line 3 and 4 need to be disabled in that case)

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: ../../.azure/variables.yaml

stages:
  - template: templates/foundationPrerequisitesManagementGroupMove.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      hubSubscriptionId: $(hubSubscriptionId)
      identitySubscriptionId: $(identitySubscriptionId)
      managementSubscriptionId: $(managementSubscriptionId)
      hubSubscriptionName: $(hubSubscriptionName)
      identitySubscriptionName: $(identitySubscriptionName)
      managementSubscriptionName: $(managementSubscriptionName)
      variableGroup: $(variableGroup)
      variableFile: ../../../.azure/variables.yaml

  - template: templates/foundationPrerequisitesResources.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      hubSubscriptionId: $(hubSubscriptionId)
      identitySubscriptionId: $(identitySubscriptionId)
      managementSubscriptionId: $(managementSubscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../../../.azure/variables.yaml