trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

parameters:
  - name: ConfigurationFile
    displayName: "Name of the configuration to use (filename without yaml extension)"
    type: string

variables:
  - template: "./input/${{ parameters.ConfigurationFile }}.yaml"
  - template: ./variables.yaml

stages:

- template: stages/governance.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(newSpoke-SubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: /variables.yaml

- template: stages/coreConnectivityResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(newSpoke-SubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: /variables.yaml

- template: stages/policyRemediation.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(newSpoke-SubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: /variables.yaml

- template: stages/coreHubConnectivityResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(newSpoke-SubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: /variables.yaml