parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: CoreWorkbookResources
  dependsOn:
  - CoreConnectivityResources
  displayName: CoreWorkbookResources
  variables:
    - name: resourceGroup
      value: $(mgmtWeu-workbooksRG_ResourceName)
    - template: ${{ parameters.variableFile }}

  jobs:
  - job: CoreWorkbookResources
    displayName: 'CoreWorkbookResources'
    steps:
      - template: /Features/BicepDeploymentRG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/subscriptionConfig.json*
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/workbooks/*.json*
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/modules/**/coreWorkbook.bicep
          subscriptionId: ${{ parameters.subscriptionId }}
          csmFile: "/modules/core/coreWorkbooks.bicep"
          resourceGroupName: $(resourceGroup)
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging')) }}:
          - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
            parameters:
              AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
              organization: ${{ parameters.organization }}
              project: ${{ parameters.project }}
              preFix: '$(outPutPrefix)'
              varMultiple: $(armOutputs)
              isSecret: false
              environment: ${{ parameters.variableGroup }}
              templateRepo: ${{ variables.templateRepo }}

  - job: reliabilityInsights
    displayName: Reliability Insights
    steps:
      - template: /Features/AzureMonitorWorkbook/Pipeline/tasks.yaml@templates
        parameters:
          subscriptionId: ${{ parameters.subscriptionId }}
          resourceGroupName: $(resourceGroup)
          csmParametersFile: /$(parameterPath)/$(resourceGroup)/reliabilityInsights.json
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
