parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: CoreNpmResources
  dependsOn:
  - CoreConnectivityResources
  - CoreBackupResources
  - CoreSecurityResources
  - CoreMonitoringResources
  displayName: CoreNpmResources
  variables:
    - name: resourceGroup
      value: $(mgmtWeu-npmRG_ResourceName)
    - template: ${{ parameters.variableFile }}

  jobs:
  - job: CoreNpmResources
    displayName: 'CoreNpmResources'
    steps:
      - task: AzurePowerShell@5
        name: registerEncryptionAtHost
        displayName: Check Encryption At Host feature
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          azurePowerShellVersion: LatestVersion
          pwsh: true
          ScriptType: 'InlineScript'
          Inline: |
            Set-AzContext -Subscription ${{ parameters.subscriptionId }} | Out-Null
            $Feature = (Get-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute").RegistrationState
            if ($Feature -eq "NotRegistered") {
              Register-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute"
            }
      - template: /Features/BicepDeploymentRG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/subscriptionConfig.json*
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/modules/**/coreNpm.bicep
          subscriptionId: ${{ parameters.subscriptionId }}
          csmFile: "/modules/core/coreNpm.bicep"
          resourceGroupName: $(resourceGroup)
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging')) }}:
          - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
            parameters:
              AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
              organization: ${{ parameters.organization }}
              project: ${{ parameters.project }}
              preFix: '$(outPutPrefix)'
              varMultiple: $(armOutputs)
              isSecret: false
              environment: ${{ parameters.variableGroup }}
              templateRepo: ${{ variables.templateRepo }}
