parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: "westeurope"
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
  - stage: Governance
    displayName: Governance
    variables:
      - template: ${{ parameters.variableFile }}

    jobs:
      - job: managementGroupMove
        displayName: Management Group Move
        steps:
          - template: /Features/SubscriptionMove/Pipeline/tasks.yaml@Templates
            parameters:
              managementGroupId: ${{ variables.managementGroupId }}
              csmParametersFile: /$(parameterPath)/governance/managementGroupMove.json
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              subscriptionId: ${{ parameters.subscriptionId }}
              subscriptionName: ${{ variables.subscriptionName }}
              location: ${{ parameters.location }}
              templateRepo: ${{ variables.templateRepo }}
              templateProject: ${{ variables.templateProject }}
              version: ${{ variables.version }}

      - ${{ if eq(variables.registerInSparkPAL, 'True') }}:
          - job: partnerRegister
            displayName: Register InSpark as Partner
            dependsOn:
              - managementGroupMove
            steps:
              - task: AzureCLI@2
                displayName: Azure CLI
                inputs:
                  azureSubscription: $(azureResourceManagerConnection)
                  powerShellErrorActionPreference: continue
                  scriptType: pscore
                  scriptLocation: inlineScript
                  inlineScript: |
                    az --version

                    $partnerInfo = az managementpartner show | ConvertFrom-Json

                    if ($partnerInfo.partnerId -ne "2134251") {
                      az managementpartner update --partner-id 2134251
                    }
                    elseif ($partnerInfo.partnerId -eq "2134251") {
                      Write-Host "$partnerInfo"
                    }
                    else {
                      az managementpartner create --partner-id 2134251
                    }

      - job: SubscriptionGovernance
        displayName: "SubscriptionGovernance"
        dependsOn:
          - ManagementGroupMove
        steps:
          - template: /Features/BicepDeploymentSub/Pipeline/tasks.yaml@Templates
            parameters:
              targetFiles: |
                /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/subscriptionConfig.jsonc
                /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/Parameters/**/subscriptionDiagnostics.json
                /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/Modules/**/governance.bicep
                /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/*.json
              subscriptionId: ${{ parameters.subscriptionId }}
              csmFile: "/modules/governance/governance.bicep"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              location: ${{ parameters.location }}
              templateRepo: ${{ variables.templateRepo }}
              templateProject: ${{ variables.templateProject }}
              version: ${{ variables.version }}

      - job: CostManagement_Get_Date
        displayName: Cost Management Alert Set Start and End Date
        dependsOn:
          - ManagementGroupMove
        steps:
          - pwsh: |
              $startDate = $((Get-Date).AddDays(1) | Get-Date -Format o);
              $endDate = $((Get-Date).AddYears(1) | Get-Date -Format o);
              Write-Host "##vso[task.setvariable variable=startDate;isOutput=true;]$startDate";
              Write-Host "##vso[task.setvariable variable=endDate;isOutput=true;]$endDate"
            name: set_date
            displayName: CostManagement Set Date

      - job: CostManagement
        displayName: Cost Management
        variables:
          startDate: $[ dependencies.CostManagement_Get_Date.outputs['set_date.startDate'] ]
          endDate: $[ dependencies.CostManagement_Get_Date.outputs['set_date.endDate'] ]
        pool: server # Required for agentless job
        dependsOn:
          - CostManagement_Get_Date
        steps:
          - template: /Features/CostAnomalyAlert/Pipeline/tasks.yaml@Templates
            parameters:
              azureServiceConnection: ${{ parameters.azureResourceManagerConnection }}
              subscriptionId: $(subscriptionId)
              subscriptionName: $(subscriptionName)
              costAnomalyAlertName: $(subscriptionName)costanomalyalert
              costAnomalyAlertDisplayName: $(subscriptionName) Cost Anomaly Alert
              startDate: $(startDate)
              endDate: $(endDate)
              notificationEmail: $(budgetEmail) # "robin.makkus@inspark.nl"
              notificationEmails: '"$(budgetEmail)"' #'"robin.makkus@inspark.nl", "xander.kaspers@inspark.nl"' # Note: The double quotes are required for the API call to work outer '' and inner "" are required.
              templateRepo: ${{ variables.templateRepo }}
              templateProject: ${{ variables.templateProject }}
              version: ${{ variables.version }}

      - job: Budgets
        displayName: Budgets
        dependsOn:
          - ManagementGroupMove
        steps:
          - template: /Features/AlertBudget/Pipeline/tasks.yaml@Templates
            parameters:
              subscriptionId: ${{ parameters.subscriptionId }}
              csmParametersFile: /$(parameterPath)/governance/budget.json
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              location: ${{ parameters.location }}
              templateRepo: ${{ variables.templateRepo }}
              templateProject: ${{ variables.templateProject }}
              version: ${{ variables.version }}
              budgetName: $(subscriptionName)-Budget

      - job: ResourceGroups
        displayName: "ResourceGroups"
        dependsOn:
          - ManagementGroupMove
        steps:
          - template: /Features/BicepDeploymentSub/Pipeline/tasks.yaml@Templates
            parameters:
              targetFiles: |
                /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/subscriptionConfig.jsonc
                /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/Modules/**/resourceGroups.bicep
              subscriptionId: ${{ parameters.subscriptionId }}
              csmFile: "/modules/governance/resourceGroups.bicep"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              location: ${{ parameters.location }}
              templateRepo: ${{ variables.templateRepo }}
              templateProject: ${{ variables.templateProject }}
              version: ${{ variables.version }}
          - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging')) }}:
              - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
                parameters:
                  AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
                  organization: ${{ parameters.organization }}
                  project: ${{ parameters.project }}
                  preFix: "$(outPutPrefix)"
                  varMultiple: $(armOutputs)
                  isSecret: false
                  environment: ${{ parameters.variableGroup }}
                  templateRepo: ${{ variables.templateRepo }}
