trigger: none

pool: default

stages:
  -stage: StageProvisionResourceGroup
    Displayname: "Stage: Provision Resource Group"
    Jobs:
      - job: JobProvisionResourceGroup
        Displayname: "Job: Provision Resource Group"
        Steps: