trigger: none

pool: default

stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/devops.ps1"
              ScriptArguments: '-location northeurope `
                -resourceGroupName "rg-404da-mktg-pdb-ne-dev-001" `
                -owner "Marketing" `
                -costCenter "112245" `
                -application "Project Day Break" `
                -description "The latest AI to do AI things" `
                -repo "https://github.com/mukilukuna/Devops"'
              FailOnStandardError: true
              azurePowerShellVersion: "LatestVersion"
