trigger: none

pool: default

stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "serviceConnectionProjectDayBreak"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/create-resource-group.ps1"
              ScriptArguments: '-location northeurope `
                -resourceGroupName "rg-404da-mktg-pdb-ne-dev-001" `
                -owner "Marketing" `
                -costCenter "112245" `
                -application "Project Day Break" `
                -description "The latest AI to do AI things" `
                -repo "https://dev.azure.com/404DataAnalytics/Project%20Day%20Break/_git/pdb-provision-resource-groups"'
              FailOnStandardError: true
              azurePowerShellVersion: "LatestVersion"
