trigger: none
pool: default
stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:
          - task: PowerShell@2
            inputs:
              targetType: "filePath"
              filePath: "$(System.DefaultWorkingDirectory)/script/devops.ps1"
              arguments: '-location westeurope `
                -resourceGroupName "rg-404da-mktg-pdb-ne-dev-001" `
                -owner "Lukuna B.V." `
                -costCenter "112245" `
                -application "Beroeps Product" `
                -description "Applicatie voor het versnellen van de productie van de Beroeps producten" `
                -repo "https://github.com/mukilukuna/Devops"'
              pwsh: true
              failOnStderr: true
              errorActionPreference: "stop"
