# This YAML configuration is for provisioning an Azure resource group.
# It includes stages and jobs for running Azure PowerShell tasks.
# The tasks call a PowerShell script with parameters to create a new resource group.
trigger: none
pool: default

stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/devops.ps1"
              ScriptArguments: '-location westeurope `
                -resourceGroupName "rg-404da-mktg-pdb-ne-dev-001" `
                -owner "Lukuna B.V." `
                -costCenter "112245" `
                -application "Beroeps Product" `
                -description "Applicatie voor het versnellen van de productie van de Beroeps producten" `
                -repo "https://github.com/mukilukuna/Devops"'
              FailOnStandardError: true
              azurePowerShellVersion: "LatestVersion"
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              ScriptType: "InlineScript"
              Inline: |
                Import-Module Microsoft.PowerShell.Security
                Install-Module microosft.powershell.Security -Scope currentuser
              errorActionPreference: "silentlyContinue"
              azurePowerShellVersion: "LatestVersion"
