trigger: none

pool:
  vmImage: 'ubuntu-latest'

# pool: "" ## Enable if self-Hosted agents are used (line 3 and 4 need to be disabled in that case)

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: variables.yaml

stages:
- template: templates/managementGroups.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(hubSubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/roleDefinitions.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(hubSubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/roleAssignments.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(hubSubscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml


