parameters:
  workloadName:
  workloadType:
  templateRepo:
  parametersPath:
  templateFileName:

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    condition: ne('${{ parameters.parametersPath }}', '')
    displayName: Replace tokens in parameters file
    inputs: # https://github.com/qetza/replacetokens-task/blob/main/tasks/ReplaceTokensV6/README.md#inputs
      sources: ${{ parameters.parametersPath }}
      ifNoFilesFound: "warn"
      missingVarAction: keep
      missingVarLog: error
      telemetryOptout: true
      tokenPattern: "custom"
      tokenPrefix: "*<"
      tokenSuffix: ">*"

  - task: PowerShell@2
    displayName: Convert bicep to json
    inputs:
      targetType: inline
      script: az bicep build -f $(System.DefaultWorkingDirectory)/${{ parameters.templateRepo }}/${{ parameters.workloadType }}/${{ parameters.workloadName }}/${{ parameters.templateFileName }}

  # - task: AzureCLI@2
  #   displayName: convert bicep to json
  #   inputs:
  #     azureSubscription: 'Bicep Templates'
  #     scriptType: "pscore"
  #     scriptLocation: "inlineScript"
  #     inlineScript: |
  #       az bicep build -f $(System.DefaultWorkingDirectory)/${{ parameters.templateRepo }}/${{ parameters.workloadType }}/${{ parameters.workloadName }}/${{ parameters.templateFileName }}
