parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: hubGatewayRouteTable
  displayName: Update Hub Gateway RouteTable
  variables:
  - name: hubResourceGroup
    value: $(hubConnectivityResourceGroup)
  - name: hubResourceGroupPath
    value: rg-hubnetworking
  - template: ${{ parameters.variableFile }}

  jobs:

  - job: gatewayRouteTable
    dependsOn:
    displayName: Update Hub Gateway Route Table
    steps:
      - template: /Solutions/GatewaySubnetRouteTable/Pipeline/tasks.yaml@Templates
        parameters:
          subscriptionId: $(hubSubscriptionId)
          resourceGroupName: $(hubResourceGroup)
          vnetName: vnet-infr-connectivity-$(environmentName)-weu-01
          csmParametersFile: /$(parameterPath)/$(hubResourceGroupPath)/routeTable.gateway.json
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
