parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: coreConnectivityResources
  displayName: Core Connectivity Resources
  variables:
  - name: resourceGroupPath
    value: rg-networking
  - name: resourceGroup
    value: rg-infr-connectivity-$(environmentName)-weu-01
  - template:  ${{ parameters.variableFile }}

  jobs:
  - job: resourceGroup
    displayName: Resource Group
    steps:
      - template: /Features/ResourceGroup/Pipeline/tasks.yaml@Templates
        parameters:
          subscriptionId: $(newSpoke-SubscriptionId)
          csmParametersFile: /$(parameterPath)/$(resourceGroupPath)/resourceGroup.json
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
          parameters:
            AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
            organization: ${{ parameters.organization }}
            project: ${{ parameters.project }}
            varKey: $(outPutPrefix)-$(resourceGroup)
            varValue: $(resourceName)
            isSecret: false
            environment: ${{ parameters.variableGroup }}
            templateRepo: $(templateRepo)

  - job: resourceGroupLock
    dependsOn:
      - resourceGroup
    displayName: Resource Group Lock
    steps:
      - template: /Features/ResourceGroupLock/Pipeline/tasks.yaml@Templates
        parameters:
          subscriptionId: ${{ parameters.subscriptionId }}
          csmParametersFile: ''
          resourceGroupName: $(resourceGroup)
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}

  - job: defaultRouteTable
    dependsOn:
      - resourceGroup
    displayName: Default Route Table
    steps:
      - template: /Features/RouteTable/Pipeline/tasks.yaml@Templates
        parameters:
          subscriptionId: ${{ parameters.subscriptionId }}
          resourceGroupName: $(resourceGroup)
          csmParametersFile: /$(parameterPath)/$(resourceGroupPath)/routeTable.default.json
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
          parameters:
            AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
            organization: ${{ parameters.organization }}
            project: ${{ parameters.project }}
            varKey: $(outPutPrefix)-routeTableDefaultResourceId
            varValue: $(resourceId)
            isSecret: false
            environment: ${{ parameters.variableGroup }}
            templateRepo: ${{ variables.templateRepo }}


