parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: policyRemediation
  displayName: Policy Remediation
  variables:
  - template:  ${{ parameters.variableFile }}

  jobs:
  - job: policyComplianceScan
    displayName: Policy Policy Compliance Scan
    steps:
      - template: /Solutions/PolicyCompliance/Pipeline/tasks.yaml@Templates
        parameters:
          id: $(newSpoke-SubscriptionId)
          type: Subscription
          startPolicyComplianceScan: $True
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}