trigger: none

pool: Azure Pipelines

stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/ResourceGroup/script/devops.ps1"
              ScriptArguments: -location "westeurope"
                -resourceGroupName "ResourceGroupBeroepsProduct"
                -owner "Lukuna B.V."`
                -costCenter "112245"
                -application "Beroeps Product"
                -description "Applicatie voor het versnellen van de productie van de Beroeps producten"
                -repo "https://github.com/mukilukuna/Devops"
              failOnStderr: true
              errorActionPreference: "stop"
              azurePowershellVersion: "LatestVersion"
