trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Bicep Plan'
  jobs:
  - job: BicepPlan
    displayName: 'Bicep Plan'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'  # Gebruik bash in plaats van PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Controleer of Bicep is geïnstalleerd
          if ! command -v bicep &> /dev/null
          then
            echo "Bicep CLI is niet geïnstalleerd. Installeren..."
            curl -L https://aka.ms/bicep/install/linux | sudo bash
          else
            echo "Bicep CLI is al geïnstalleerd."
          fi

          # Valideer het Bicep-bestand met parameters
          bicep build main.bicep --parameters dev.bicepparam

        displayName: 'Bicep Build en Valideer'

- stage: Deploy
  displayName: 'Bicep Deploy'
  jobs:
  - job: BicepDeploy
    displayName: 'Bicep Deploy'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'  # Gebruik bash in plaats van PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Controleer of Bicep is geïnstalleerd
          if ! command -v bicep &> /dev/null
          then
            echo "Bicep CLI is niet geïnstalleerd. Installeren..."
            curl -L https://aka.ms/bicep/install/linux | sudo bash
          else
            echo "Bicep CLI is al geïnstalleerd."
          fi

          # Implementeer het Bicep-sjabloon met parameters
          az deployment group create \
            --resource-group NetworkRG \
            --template-file main.bicep \
            --parameters dev.bicepparam

        displayName: 'Bicep Implementatie'
