trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Bicep Plan'
  jobs:
  - job: BicepPlan
    displayName: 'Bicep Plan'
    steps:
    - checkout: self
    - script: |
        echo "Current working directory: $(pwd)"
        ls -R
      displayName: 'Debug: List Files'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'  # Gebruik bash in plaats van PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Navigeer naar de map met de Bicep-bestanden
          cd Bicep/Network
          # Verifieer of bestanden bestaan
          ls -l main.bicep dev.bicepparam

          # Install Bicep CLI if missing
          if ! command -v bicep &> /dev/null; then
            sudo curl -L https://aka.ms/bicep/install/linux | sudo bash
          fi

          bicep build main.bicep
        displayName: 'Bicep Build en Valideer'

- stage: Deploy
  displayName: 'Bicep Deploy'
  jobs:
  - job: BicepDeploy
    displayName: 'Bicep Deploy'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'  # Gebruik bash in plaats van PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Navigeer naar de map met de Bicep-bestanden
          cd Bicep/Network
          
          az deployment group create \
            --resource-group NetworkRG \
            --template-file main.bicep \
            --parameters @dev.bicepparam
        displayName: 'Bicep Implementatie'
