trigger:
- main  # Voert de pipeline automatisch uit wanneer er iets wordt gepusht naar de 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # De agent waarop de pipeline draait

variables:
  azureSubscription: 'ServiceConnectionProjectAnsible'  # De naam van je Azure Service Connection
  resourceGroupName: 'your-resource-group'  # De naam van je Resource Group in Azure
  location: 'WestEurope'  # De locatie van je Azure Resources

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
       echo "Huidige werkdirectory:"
      pwd
      echo "Inhoud van de huidige directory:"
      ls -la
      echo "Recursieve inhoud van alle directories:"
      ls -laR
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file ./main.bicep

  displayName: 'Deploy Bicep Template'
