trigger:
- main

variables:
  - group: avd-secrets  # Linked to Azure Key Vault for secrets (e.g., VM adminPassword)

stages:
- stage: Validate
  displayName: Validate Bicep
  jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'
        script: |
          cd bicep\AVD-infra
          # Install Bicep CLI
          az bicep install
          az deployment group create \
            --resource-group avd-dev-rg \  # Explicitly define the RG
            --template-file main.bicep \
            --parameters @dev.bicepparam

          # Lint and validate
          bicep build avd-infra/main.bicep
          bicep lint avd-infra/main.bicep

- stage: Deploy_Dev
  displayName: Deploy to Dev
  dependsOn: Validate
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'avd-service-connection'
        scriptType: 'bash'
        script: |
          az deployment group create \
            --resource-group avd-dev-rg \
            --template-file avd-infra/main.bicep \
            --parameters @avd-infra/parameters/dev.bicepparam

- stage: Deploy_Prod
  displayName: Deploy to Prod
  dependsOn: Deploy_Dev
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'avd-service-connection'
        scriptType: 'bash'
        script: |
          az deployment group create \
            --resource-group avd-prod-rg \
            --template-file avd-infra/main.bicep \
            --parameters @avd-infra/parameters/prod.bicepparam