trigger:
- main

variables:
  vmAdminUsername: 'avdadmin'
  avdHostPoolName: 'my-avd-pool'

stages:
- stage: Validate
  displayName: Validate Bicep
  jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'  # Correct casing
        inlineScript: |  # Use inlineScript, not script
          # Validate Bicep files
          cd bicep/AVD-infra  # Use forward slashes for Linux
          az bicep install
          bicep build main.bicep
          bicep lint main.bicep

- stage: Deploy_Dev
  displayName: Deploy to Dev
  dependsOn: Validate
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'  # Required for inline scripts
        inlineScript: |
          cd bicep/AVD-infra
          az deployment group create \
            --resource-group avd-dev-rg \
            --template-file main.bicep \
            --parameters @parameters/dev.bicepparam

- stage: Deploy_Prod
  displayName: Deploy to Prod
  dependsOn: Deploy_Dev
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(098e34b6-d88e-447e-ba9a-245275343d63)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'  # Required for inline scripts
        inlineScript: |
          cd bicep/AVD-infra
          az deployment group create \
            --resource-group avd-prod-rg \
            --template-file main.bicep \
            --parameters @parameters/prod.bicepparam