parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: CorePrivateLinkZonesResources
  dependsOn: CoreConnectivityResources
  displayName: CorePrivateLinkZonesResources
  variables:
    - name: resourceGroup
      value: $(idenWeu-privateLinkZonesRG_ResourceName)
    - template: ${{ parameters.variableFile }}

  jobs:
  - job: CorePrivateLinkDnsZonesResources
    displayName: 'CorePrivateLinkDnsZonesResources'
    steps:
      - template: /Features/BicepDeploymentRG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/subscriptionConfig.jsonc
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/modules/**/corePrivateLinkDnsZones.bicep
          subscriptionId: ${{ parameters.subscriptionId }}
          csmFile: "/modules/core/corePrivateLinkDnsZones.bicep"
          resourceGroupName: $(resourceGroup)
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
