parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: hubSubscriptionId
    type: string
  - name: hubSubscriptionName
    type: string
  - name: identitySubscriptionId
    type: string
  - name: identitySubscriptionName
    type: string
  - name: managementSubscriptionId
    type: string
  - name: managementSubscriptionName
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: corporateMGandSubscriptionMove
  displayName: Corporate MG and move subscriptions
  variables:
    - template: ${{ parameters.variableFile }}
  jobs:
  - job: ManagementGroup
    displayName: Deploy Management Groups
    steps:
      - template: /Features/BicepDeploymentMG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: /prerequisites/modules/foundationMgPrerequisites.bicep
          csmFile: /prerequisites/modules/foundationMgPrerequisites.bicep
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
          overrideParameters: -customerMgName $(CustomerManagementGroup) -managementGroupIdPrefix "mg-"
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'), eq(variables['Build.SourceBranch'], 'refs/heads/foundationV2')) }}:
          - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
            parameters:
              AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
              organization: ${{ parameters.organization }}
              project: ${{ parameters.project }}
              preFix: 'managementGroup'
              varMultiple: $(armOutputs)
              isSecret: false
              environment: ${{ parameters.variableGroup }}
              templateRepo: ${{ variables.templateRepo }}

  - job: customroledefinitions
    displayName: Deploy Custom Role Definitions
    dependsOn: ManagementGroup
    steps:
      - template: /Features/BicepDeploymentMG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: '/prerequisites/modules/foundationCustomRoleDefinitionsPrerequisites.bicep'
          csmFile: "/prerequisites/modules/foundationCustomRoleDefinitionsPrerequisites.bicep"
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
          overrideParameters: -customerMgName $(CustomerManagementGroup)
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'),  eq(variables['Build.SourceBranch'], 'refs/heads/foundationV2') ) }}:
          - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
            parameters:
              AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
              organization: ${{ parameters.organization }}
              project: ${{ parameters.project }}
              preFix: 'managementGroup'
              varMultiple: $(armOutputs)
              isSecret: false
              environment: ${{ parameters.variableGroup }}
              templateRepo: ${{ variables.templateRepo }}

  - job: managementGroupMoveHub
    displayName: Management Group Move Hub
    dependsOn: ManagementGroup
    steps:
      - template: /Features/SubscriptionMove/Pipeline/tasks.yaml@Templates
        parameters:
          csmParametersFile: /prerequisites/$(parameterPath)/managementGroupMove.hubsubscription.json
          azureResourceManagerConnection: $(azureResourceManagerConnection)
          managementGroupId: $(managementGroup-customerMg_ResourceName)
          subscriptionId: ${{ parameters.hubSubscriptionId }}
          subscriptionName: ${{ parameters.hubSubscriptionName }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}

  - job: managementGroupMoveIdentity
    displayName: Management Group Move Identity
    dependsOn: ManagementGroup
    steps:
      - template: /Features/SubscriptionMove/Pipeline/tasks.yaml@Templates
        parameters:
          csmParametersFile: /prerequisites/$(parameterPath)/managementGroupMove.identitysubscription.json
          azureResourceManagerConnection: $(azureResourceManagerConnection)
          managementGroupId: $(managementGroup-customerMg_ResourceName)
          subscriptionId: ${{ parameters.identitySubscriptionId }}
          subscriptionName: ${{ parameters.identitySubscriptionName }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}

  - job: managementGroupMoveManagement
    displayName: Management Group Move Management
    dependsOn: ManagementGroup
    steps:
      - template: /Features/SubscriptionMove/Pipeline/tasks.yaml@Templates
        parameters:
          csmParametersFile: /prerequisites/$(parameterPath)/managementGroupMove.managementsubscription.json
          azureResourceManagerConnection: $(azureResourceManagerConnection)
          managementGroupId: $(managementGroup-customerMg_ResourceName)
          subscriptionId: ${{ parameters.managementSubscriptionId }}
          subscriptionName: ${{ parameters.managementSubscriptionName }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}