trigger: none
pool: default
stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "ServiceConnectionProjectAnsible"
              targetType: "filePath"
              filePath: "$(System.DefaultWorkingDirectory)/ResourceGroup/script/devops.ps1"
              arguments: >
                -location "westeurope"
                -resourceGroupName "ResourceGroupBeroepsProduct"
                -owner "Lukuna B.V."
                -costCenter "112245"
                -application "Beroeps Product"
                -description "Applicatie voor het versnellen van de productie van de Beroeps producten"
                -repo "https://github.com/mukilukuna/Devops"
              #                -ServicePrincipalId "$(ServicePrincipalId)"
              #                -ServicePrincipalKey "$(ServicePrincipalKey)"
              #                -TenantId "$(TenantId)"
              pwsh: true
              failOnStderr: true
              errorActionPreference: "stop"
              azurePowershellVersion: "LatestVersion"
#    variables:
#      ServicePrincipalId: "fda4fffb-a2a7-4aef-aa72-ec775ceaf764"
#      TenantId: "62e222e6-5ad4-45d1-88c4-1b18d2bedfda"
