trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: variables.yaml

stages:
  - template: templates/firewallRuleCollectionFoundation.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml

  - template: templates/firewallRuleCollectionConnectivity.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml

  - template: templates/firewallRuleCollectionIdentity.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml

  - template: templates/firewallRuleCollectionManagement.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml