trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: variables.yaml

stages:
  - template: templates/firewallRuleCollectionSubAvdOfficePWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml
  
  - template: templates/firewallRuleCollectionSubCcsWorkloadDWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml

  - template: templates/firewallRuleCollectionSubCcsWorkloadTWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml
  
  - template: templates/firewallRuleCollectionSubCcsWorkloadAWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml
  
  - template: templates/firewallRuleCollectionSubCcsWorkloadPWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml

  - template: templates/firewallRuleCollectionSubCfpWorkloadDWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml
  
  - template: templates/firewallRuleCollectionSubCfpWorkloadTWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml
  
  - template: templates/firewallRuleCollectionSubCfpWorkloadAWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml
  
  - template: templates/firewallRuleCollectionSubCfpWorkloadPWeu01.yaml
    parameters:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      variableGroup: $(variableGroup)
      variableFile: ../variables.yaml