trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: variables.yaml

stages:
- template: templates/vpnConnections-OnPrem.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml
