trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: variables.yaml

stages:
- template: templates/governance.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/applicationSecurityGroupResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreConnectivityResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreMonitoringResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreAutomationResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreSecurityResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreBackupResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreWorkbookResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreUpdateManagementResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/coreNpmResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml

- template: templates/networkWatcherResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml
