trigger: none

schedules:
  - cron: "0 */6 * * *"
    displayName: 6 Hours Auto Remediation
    branches:
      include:
        - main
    always: true

pool:
  vmImage: "ubuntu-latest"

# pool: "" ## Enable if self-Hosted agents are used (line 3 and 4 need to be disabled in that case)

variables:
  - name: customerMgId
    value: mg-OpGroen
  - template: variables.yaml

stages:
  - stage: AutoRemediation
    displayName: Auto Remediation
    jobs:
      - job: AutoRemediationCustomerMg
        displayName: Auto Remediation Customer Mg
        steps:
          - task: AzurePowerShell@5
            displayName: AutoRemediation
            inputs:
              azureSubscription: ${{ variables.azureResourceManagerConnection }}
              ScriptType: "FilePath"
              ScriptPath: "scripts/Start-PolicyRemediation.ps1"
              ScriptArguments: '-Id "$(managementGroup-customerMg_ResourceName)" -Type "ManagementGroup" -RunAsJob $True -startPolicyComplianceScan $False'
              azurePowerShellVersion: "LatestVersion"
