trigger: none

schedules:
  - cron: "0 20 * * *"
    displayName: Cleanup every day at 8 PM
    branches:
      include:
        - main
    always: true

pool:
  vmImage: "ubuntu-latest"

# pool: "" ## Enable if self-Hosted agents are used (line 3 and 4 need to be disabled in that case)

variables:
  - template: variables.yaml

stages:
  - stage: Cleanup
    jobs:
      - job: Cleanup_PROD_RBAC_Assignments
        displayName: PROD - Remove Orphaned RBAC Assignments
        steps:
          - task: AzurePowerShell@5
            displayName: "Remove-OrphanedRBACAssignments.ps1"
            inputs:
              azureSubscription: ${{ variables.azureResourceManagerConnection }}
              ScriptType: "FilePath"
              ScriptPath: "scripts/Remove-OrphanedRBACAssignments.ps1"
              ScriptArguments: -ManagementGroupName "$(managementGroup-customerMg_ResourceName)"
              azurePowerShellVersion: "LatestVersion"
            env:
              SubscriptionId: $(subscriptionId)

      - job: Cleanup_CANARY_RBAC_Assignments
        displayName: CANARY - Remove Orphaned RBAC Assignments
        steps:
          - task: AzurePowerShell@5
            displayName: "Remove-OrphanedRBACAssignments.ps1"
            inputs:
              azureSubscription: ${{ variables.azureResourceManagerConnection }}
              ScriptType: "FilePath"
              ScriptPath: "scripts/Remove-OrphanedRBACAssignments.ps1"
              ScriptArguments: -ManagementGroupName "$(canary-managementGroup-customerMg_ResourceName)"
              azurePowerShellVersion: "LatestVersion"
            env:
              SubscriptionId: $(subscriptionId)
