trigger: none

schedules:
  - cron: "0 1 1 * *"
    displayName: Cleanup every 1st day of the month at 01:00
    branches:
      include:
        - main
    always: true

pool:
  vmImage: "ubuntu-latest"

# pool: "" ## Enable if self-Hosted agents are used (line 3 and 4 need to be disabled in that case)

variables:
  - template: variables.yaml

stages:
  - stage: CleanupDeploymentHistory
    displayName: Cleanup Deployment History
    jobs:
      - job: Cleanup_Deployment_History_Customer_MG
        displayName: Production MG
        steps:
          - task: AzurePowerShell@5
            displayName: "Start-DeleteManagementGroupDeploymentHistory.ps1"
            inputs:
              azureSubscription: ${{ variables.azureResourceManagerConnection }}
              ScriptType: "FilePath"
              ScriptPath: "scripts/Start-DeleteManagementGroupDeploymentHistory.ps1"
              ScriptArguments: -ManagementGroupId "$(managementGroup-customerMg_ResourceName)"
              azurePowerShellVersion: "LatestVersion"

      - job: Cleanup_Deployment_History_Canary_Customer_MG
        displayName: Canary MG
        steps:
          - task: AzurePowerShell@5
            displayName: "Start-DeleteManagementGroupDeploymentHistory.ps1"
            inputs:
              azureSubscription: ${{ variables.azureResourceManagerConnection }}
              ScriptType: "FilePath"
              ScriptPath: "scripts/Start-DeleteManagementGroupDeploymentHistory.ps1"
              ScriptArguments: -ManagementGroupId "$(canary-managementGroup-customerMg_ResourceName)"
              azurePowerShellVersion: "LatestVersion"
