parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: CoreConnectivityResources
  displayName: CoreConnectivityResources
  variables:
    - name: resourceGroup
      value: $(connWeu-connectivityRG_ResourceName)
    - template: ${{ parameters.variableFile }}

  jobs:
  - job: GatewayRouteTable
    displayName: GatewayRouteTable
    steps:
      - template: /Solutions/GatewaySubnetRouteTable/Pipeline/tasks.yaml@Templates
        parameters:
          subscriptionId: ${{ parameters.subscriptionId }}
          resourceGroupName: $(resourceGroup)
          vnetName: vnet-infr-connectivity-p-weu-01
          csmParametersFile: /$(parameterPath)/$(resourceGroup)/routeTable.gateway.json
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging')) }}:
        - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
          parameters:
            AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
            organization: ${{ parameters.organization }}
            project: ${{ parameters.project }}
            varKey: $(outPutPrefix)-routeTableGateway_ResourceId
            varValue: $(resourceId)
            isSecret: false
            environment: ${{ parameters.variableGroup }}
            templateRepo: ${{ variables.templateRepo }}

  - job: CoreConnectivityResources
    displayName: 'CoreConnectivityResources'
    dependsOn:
    - GatewayRouteTable
    steps:
      - template: /Features/BicepDeploymentRG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/subscriptionConfig.jsonc
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/modules/**/coreConnectivity.bicep
          subscriptionId: ${{ parameters.subscriptionId }}
          csmFile: "/modules/core/coreConnectivity.bicep"
          resourceGroupName: $(resourceGroup)
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging')) }}:
          - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
            parameters:
              AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
              organization: ${{ parameters.organization }}
              project: ${{ parameters.project }}
              preFix: '$(outPutPrefix)'
              varMultiple: $(armOutputs)
              isSecret: false
              environment: ${{ parameters.variableGroup }}
              templateRepo: ${{ variables.templateRepo }}
