parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: FirewallRuleCollectionsFoundation
  displayName: FirewallRuleCollectionsFoundation
  variables:
    - name: resourceGroup
      value: $(connWeu-connectivityRG_ResourceName)
    - template: ${{ parameters.variableFile }}

  jobs:
  - job: FirewallRuleCollections
    displayName: 'Firewall Rule Collections'
    dependsOn: []
    steps:
      - template: /Features/BicepDeploymentRG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/configs/subscriptionConfig.jsonc
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/modules/firewallRules/*.bicep
            /$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)/configs/firewallRules/*.json
          subscriptionId: ${{ parameters.subscriptionId }}
          csmFile: "/modules/firewallRules/firewallRuleCollectionsFoundation.bicep"
          resourceGroupName: $(resourceGroup)
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}

