trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: Templates
      type: git
      name: Foundation/Templates  ## Update based on DevOps organization and project

variables:
  - template: variables.yaml

parameters:
  - name: delayRemoval
    displayName: "Delay of removal Bastion resource Gourp (in minutes, maximum 360)"
    type: string
    default: '60'

stages:

- template: templates/bastionResources.yaml
  parameters:
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    variableGroup: $(variableGroup)
    variableFile: ../variables.yaml
    delayRemoval:  ${{ parameters.delayRemoval }}