parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: rbac
  displayName: Deploy Role Assignments
  variables:
    - template: ${{ parameters.variableFile }}
  jobs:
  - job: rbac
    displayName: Deploy Role Assignments
    steps:
      - template: /Features/BicepDeploymentMG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/Foundation/configs/*.json
            /$(System.DefaultWorkingDirectory)/Foundation/modules/*.bicep
          csmFile: "/modules/foundationRoleAssignments.bicep"
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
