parameters:
  - name: azureResourceManagerConnection
    type: string
  - name: location
    type: string
    default: 'westeurope'
  - name: subscriptionId # Replace with or add managementGroupId if needed
    type: string
  - name: variableGroup
    type: string
  - name: variableFile
    type: string
  - name: AZURE_DEVOPS_EXT_PAT
    type: string
    default: $(System.AccessToken)
  - name: organization
    type: string
    default: $(System.TeamFoundationCollectionUri)
  - name: project
    type: string
    default: $(System.TeamProject)

stages:
- stage: customroledefinitions
  displayName: Deploy Custom Role Definitions
  variables:
    - template: ${{ parameters.variableFile }}
  jobs:
  - job: customroledefinitions
    displayName: Deploy Custom Role Definitions
    steps:
      - template: /Features/BicepDeploymentMG/Pipeline/tasks.yaml@Templates
        parameters:
          targetFiles: |
            /$(System.DefaultWorkingDirectory)/Foundation/configs/*.json
          csmFile: "/modules/foundationCustomRoleDefinitions.bicep"
          azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
          location: ${{ parameters.location }}
          templateRepo: ${{ variables.templateRepo }}
          templateProject:  ${{ variables.templateProject }}
          version: ${{ variables.version }}
      - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/staging')) }}:
          - template: /.Global/Pipelines/addVariableToVariableGroup.yaml@Templates
            parameters:
              AZURE_DEVOPS_EXT_PAT: ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
              organization: ${{ parameters.organization }}
              project: ${{ parameters.project }}
              preFix: ''
              varMultiple: $(armOutputs)
              isSecret: false
              environment: ${{ parameters.variableGroup }}
              templateRepo: ${{ variables.templateRepo }}